"""empty message

Revision ID: 69b1bb0b561c
Revises: 3cce59c38d33
Create Date: 2019-11-18 17:09:06.989761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b1bb0b561c'
down_revision = '3cce59c38d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('imgLoc', sa.String(length=256), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'imgLoc')
    # ### end Alembic commands ###
